version: '5 and 6'
services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    deploy:
      replicas: 2
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end