# Use la última versión de Ubuntu como base
FROM ubuntu:latest

# Actualiza APT
RUN apt-get update

# Actualiza el software instalado
RUN apt-get upgrade -y

# Ejecuta un comando que imprime "Hello, World!" en el terminal
CMD echo "Hello, World!"
